### PR TITLE
smaller buffer token list

### PR DESCRIPTION
**Pull request by josojo**
The research in here: https://docs.google.com/document/d/10Xi4O22p6JhGgEjABGf45ljRTJ7ZB0f8ZbPO0c2Bt28/edit#
showed that using a fewer buffer token at roughly 1M buffer funds, results in a 10% degree of overall gas costs. 
Hence, I am updating the list for the cowdexAgg solver.

But then we should also update it in the other solvers and deny the withdraw service to withdraw these tokens in future PRs
@marcovc  and @twalth3r, if you approve this PR, please copy the list to your solvers as well. I would then take care of the withdrawservice

I have hand-selected the buffer tokens:
- I prioritized the coins traded the most according to dune pie chart: 
https://dune.xyz/gnosis.protocol/Gnosis-Protocol-V2 
- I did not choose MIM, as there is a higher risk that the value defaults to 0
- I did already added cow token, such that we can support it from the start

### CODE REVIEW

**Review by twalth3r — APPROVED** [review]
Makes sense!
Do you think this list needs regular maintenance, and how to notice when it's the right time to update it?

**Comment by josojo** [comment]
No, I don't think it needs regular updating. For the very optimal strategies, sure one would need it, but I think its fine to keep it static for the time beings

**Review by marcovc — APPROVED** [review]
Good that you did this research!

**Comment by marcovc** [comment]
Looking at the linked doc, I noticed that we only settle internally 1% more of trades when we reduce the buffere to 10. What am I missing?

**Comment by marcovc** [comment]
>  I would then take care of the withdrawservice

If we were selling forbidden tokens then they would slowly go away, and a manual transaction was not needed.

**Comment by marcovc** [comment]
I was also thinking that going to ~200 could be a better idea. 

The reason is that we are implicitly relying on the past=future assumption here, but the truth is that we don't know what those 10 are. So picking 200 now that will include those future best 10 seem like a more sure bet than picking those future best 10 now.

Of course then one could argue that then it would be better to stay as we are. But that is not true because we only loose 1% from going from 10 to 200 tokens.

To compute this correctly we would need to know how often the best 10 change in time. We could estimate this as well.

**Comment by fleupold** [comment]
We also need to configure the "market makeable token list" in gpv2, don't we? There, it's just a config variable pointing to an URL. Maybe that would make sense in the other repos as well, given that the DAO will curate that list in the future?

**Comment by josojo** [comment]
>If we were selling forbidden tokens then they would slowly go away, and a manual transaction was not needed.

This is how quasimodo will do it. Quasimodo is the only solver that has the implementation that only one buffer token needs to be in the token allowlist. Hence Quasimodo will push all the small reserves slowly into the main buffer tokens. :) 

>The reason is that we are implicitly relying on the past=future assumption here, but the truth is that we don't know what those 10 are.

I think that the most traded tokens are quite stable: since most TOKENS pools have a ETH-TOKEN, and STABLETOKEN- TOKEN trades are common, we can always make the ETH-STABLECOIN part of the internal buffer. Hence stable tokens + ETH and BTC are a must. And this is already 50% of the tokens in the current list.

I wouldn't go for 200 tokens, as in the beginning our effective usd-holdings in the buffers will be smaller than 1M, as we will keep a lot of funds distributed over the 1500 Tokens, as we have it right now.

>We also need to configure the "market makeable token list" in gpv2, don't we? There, it's just a config variable pointing to an URL. Maybe that would make sense in the other repos as well, given that the DAO will curate that list in the future?

Yes, once this PR is merged, we can point to the list of the cow-dex-solver also from the backend. Then we only need to maintain the list in this repo. For the withdraw-service I would also use this REPO as a reference.
Otherwise, we could also create a new REPO: "solver-configuration" and put the leading list in there.

**Comment by marcovc** [comment]
> Quasimodo is the only solver that has the implementation that only one buffer token needs to be in the token allowlist.

Not anymore, Tom just finished a PR for a more clever buffer usage that will not let us sell forbidden buffers. But I think it is possible to change that, right @twalth3r ?

**Comment by josojo** [comment]
>Not anymore, Tom just finished a PR for a more clever buffer usage that will not let us sell forbidden buffers. But I think it is possible to change that, right @twalth3r ?

I think it would be nice, if we have one solver that is able to push non-allowlisted buffer reserves into the allowlisted-buffer reserves.

If you guys want, I can change the cowdexag solver to do that

**Comment by twalth3r** [comment]
> I think it would be nice, if we have one solver that is able to push non-allowlisted buffer reserves into the allowlisted-buffer reserves.

Yes, I can also do that for Quasimodo/MIP - should I?

**Comment by josojo** [comment]
>Yes, I can also do that for Quasimodo/MIP - should I?

If you volunteer that would be great!

**Pull request merged**
